import type { Metadata } from "next";
import { AppStoreProvider } from "@/state/providers/app-store-provider";
import { createClient } from "@/lib/supabase/server";
import { Suspense } from "react";
import localFont from "next/font/local";
import AppToaster from "@/modules/common/layout/AppToaster";
import "./globals.css";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense>
          <AppToaster />
        </Suspense>
        <div className='flex flex-col'>
          <header className="h-10 bg-gradient-to-r from-purple-700 from-10% via-purple-600 via-30% to-indigo-600 to-90%">

          </header>
          <main className="flex-grow">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
